name: Release

on:
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  build:
    runs-on: macos-15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: "1.88.0"

      - name: Extract version from Cargo.toml
        id: cargo-version
        run: echo "VERSION=$(grep '^version =' Cargo.toml | awk -F'"' '{print $2}')" >> $GITHUB_ENV

      - name: Build project
        run: cargo build --release --target aarch64-apple-darwin

      - name: Create archive
        run: |
          cd target/aarch64-apple-darwin/release
          tar -czvf semantic-git-cz-aarch64-apple-darwin.tar.gz semantic-git-cz

      - name: Upload release asset
        uses: actions/upload-artifact@v4
        with:
          name: semantic-git-cz-aarch64-apple-darwin
          path: target/aarch64-apple-darwin/release/semantic-git-cz-aarch64-apple-darwin.tar.gz

  create_tag_and_release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract version from Cargo.toml
        id: cargo-version
        run: echo "VERSION=$(grep '^version =' Cargo.toml | awk -F'"' '{print $2}')" >> $GITHUB_ENV

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: semantic-git-cz-aarch64-apple-darwin
          path: .

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "v${{ env.VERSION }}" \
            --title "Release v${{ env.VERSION }}" \
            --notes "Automatic release by GitHub Actions." \
            ./semantic-git-cz-aarch64-apple-darwin.tar.gz
