name: Release

on:
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  build:
    runs-on: macos-15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: "1.88.0"
          
      - name: Cache Rust dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Extract version from Cargo.toml
        id: cargo-version
        run: echo "VERSION=$(grep '^version =' Cargo.toml | awk -F'"' '{print $2}')" >> $GITHUB_ENV

      - name: Run security audit
        run: |
          cargo install cargo-audit
          cargo audit

      - name: Build project
        run: cargo build --release --target aarch64-apple-darwin

      - name: Create archive
        run: |
          mkdir -p target/aarch64-apple-darwin/release/${{ env.VERSION }}
          cd target/aarch64-apple-darwin/release
          tar -czvf ${{ env.VERSION }}/semantic-git-cz-${{ env.VERSION }}-aarch64-apple-darwin.tar.gz semantic-git-cz
          
      - name: Generate checksum
        run: |
          cd target/aarch64-apple-darwin/release/${{ env.VERSION }}
          shasum -a 256 semantic-git-cz-${{ env.VERSION }}-aarch64-apple-darwin.tar.gz > semantic-git-cz-${{ env.VERSION }}-aarch64-apple-darwin.tar.gz.sha256

      - name: Upload release asset
        uses: actions/upload-artifact@v4
        with:
          name: semantic-git-cz-aarch64-apple-darwin
          path: |
            target/aarch64-apple-darwin/release/${{ env.VERSION }}/semantic-git-cz-${{ env.VERSION }}-aarch64-apple-darwin.tar.gz
            target/aarch64-apple-darwin/release/${{ env.VERSION }}/semantic-git-cz-${{ env.VERSION }}-aarch64-apple-darwin.tar.gz.sha256

  create_tag_and_release:
    needs: build
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract version from Cargo.toml
        id: cargo-version
        run: echo "VERSION=$(grep '^version =' Cargo.toml | awk -F'"' '{print $2}')" >> $GITHUB_ENV

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: semantic-git-cz-aarch64-apple-darwin
          path: .
          
      - name: Verify checksum
        run: shasum -a 256 -c semantic-git-cz-${{ env.VERSION }}-aarch64-apple-darwin.tar.gz.sha256

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          CHECKSUM=$(cat semantic-git-cz-${{ env.VERSION }}-aarch64-apple-darwin.tar.gz.sha256)
          gh release create "v${{ env.VERSION }}" \
            --title "Release v${{ env.VERSION }}" \
            --notes "Automatic release by GitHub Actions.

